from django.urls import path
from . import views

urlpatterns = [
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('support-tickets/', views.TicketCreateAPIView.as_view(), name='support-ticket-create'),
    path('support-tickets/close/', views.TicketCloseAPIView.as_view(), name='support-ticket-close'),
    path('discord-heartbeat/', views.DiscordHeartbeatView.as_view(), name='discord-heartbeat'),
    path('discord-pickup-role-events/claim/', views.DiscordPickupRoleEventClaimView.as_view(), name='discord-pickup-role-event-claim'),
    path('discord-pickup-role-events/complete/', views.DiscordPickupRoleEventCompleteView.as_view(), name='discord-pickup-role-event-complete'),
    path('discord-pickup-role-assignments/', views.DiscordPickupRoleAssignmentsView.as_view(), name='discord-pickup-role-assignments'),
    path('discord-pickup-schedule-dates/', views.DiscordPickupScheduleDatesView.as_view(), name='discord-pickup-schedule-dates'),
    path('discord-pickup-member-dates/', views.DiscordPickupMemberDatesView.as_view(), name='discord-pickup-member-dates'),
    path('discord-pickup-lifecycle/claim/', views.DiscordPickupLifecycleClaimView.as_view(), name='discord-pickup-lifecycle-claim'),
    path('discord-pickup-lifecycle/finish/', views.DiscordPickupLifecycleFinishView.as_view(), name='discord-pickup-lifecycle-finish'),
    path('dispatch/', views.DispatchView.as_view(), name='dispatch'),
    path('my-orders/', views.UserOrdersView.as_view(), name='my-orders'),
    path('admin-history/', views.AdminOrderHistoryView.as_view(), name='admin-order-history'),
    path('overdue/', views.OverdueOrdersView.as_view(), name='overdue-orders'),
    path('purchase-limits/', views.PurchaseLimitsView.as_view(), name='purchase-limits'),
    path('cancel/', views.CancelOrderView.as_view(), name='cancel-order'),
    path('<uuid:order_id>/cancel/', views.AdminCancelOrderView.as_view(), name='admin-cancel-order'),
    path('<uuid:order_id>/cancel-items/', views.AdminCancelOrderItemsView.as_view(), name='admin-cancel-order-items'),
    path('respond-counteroffer/', views.RespondCounterOfferView.as_view(), name='respond-counteroffer'),
    path('reschedule/', views.RescheduleOrderView.as_view(), name='reschedule-order'),
    path('receipt/<uuid:order_id>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('coupons/', views.CouponListCreateView.as_view(), name='coupon-list-create'),
    path('coupons/<int:pk>/', views.CouponDetailView.as_view(), name='coupon-detail'),
    path('validate-coupon/', views.ValidateCouponView.as_view(), name='validate-coupon'),
    path('active-timeslots/', views.ActiveTimeslotsView.as_view(), name='active-timeslots'),
    path('admin-dashboard/', views.AdminDashboardView.as_view(), name='admin-dashboard'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/sync/', views.CartSyncView.as_view(), name='cart-sync'),
    path('<uuid:order_id>/merge-cart/', views.MergeCartIntoOrderView.as_view(), name='merge-cart'),
    # Admin POS endpoints
    path('admin/users/search/', views.AdminUserSearchView.as_view(), name='admin-user-search'),
    path('admin/pos-inventory/', views.AdminPOSInventoryView.as_view(), name='admin-pos-inventory'),
    path('admin/create-order/', views.AdminCreateOrderView.as_view(), name='admin-create-order'),
]