# Generated by Django 6.0.4 on 2026-04-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="discord_handle",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
