# Generated by Django 6.0.4 on 2026-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_seed_pokemon_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="trade_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
