# Generated by Django 6.0.4 on 2026-04-08 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('venmo', 'Venmo'), ('zelle', 'Zelle'), ('paypal', 'PayPal')], max_length=10)),
                ('delivery_method', models.CharField(choices=[('scheduled', 'Scheduled Campus Pickup'), ('asap', 'ASAP Downtown Pickup')], max_length=10)),
                ('discord_handle', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('pickup_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pickupslot')),
            ],
        ),
    ]
