# Generated by Django 6.0.4 on 2026-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_trade_card_name_order_trade_card_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buy_if_trade_denied",
            field=models.BooleanField(default=False),
        ),
    ]
