# Generated by Django 6.0.4 on 2026-04-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_tradecarditem_base_market_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="requires_rescheduling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="reschedule_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
