# Generated by Django 6.0.4 on 2026-04-09 04:33
# Manually split into 3 steps for SQLite compatibility with unique UUID backfill.

import uuid
from django.db import migrations, models


def populate_uuids(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.order_id = uuid.uuid4()
        order.save(update_fields=['order_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_requires_rescheduling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="backup_payment_method",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        # Step 1: Add order_id without unique constraint
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate existing rows with unique UUIDs
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        # Step 3: Make non-nullable and unique
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="trade_overage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
