# Generated by Django 6.0.4 on 2026-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_counteroffer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="counteroffer_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the counteroffer auto-expires", null=True
            ),
        ),
    ]
