# Generated by Django 6.0.4 on 2026-04-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_resolution_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flat dollar discount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage discount (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Dollar amount discounted by coupon",
                max_digits=10,
            ),
        ),
    ]
