# Generated by Django 6.0.4 on 2026-04-15 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_max_per_week_item_max_total_per_user"),
        ("orders", "0021_order_is_acknowledged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="min_order_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum cash total (after trade credit) required",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="requires_cash_only",
            field=models.BooleanField(
                default=False,
                help_text="If True, any trade credit disqualifies this coupon",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="specific_product",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, discount applies only to this product's line item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.item",
            ),
        ),
    ]
