# Generated by Django 6.0.4 on 2026-04-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_order_pickup_rescheduled_by_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("venmo", "Venmo"),
                    ("zelle", "Zelle"),
                    ("paypal", "PayPal"),
                    ("cash", "Cash"),
                    ("trade", "Trade-In"),
                    ("cash_plus_trade", "Cash + Trade Difference"),
                ],
                max_length=20,
            ),
        ),
    ]
