# Generated by Django 6.0.4 on 2026-04-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_add_orderitem_and_nullable_order_fields"),
        ("orders", "9999_migrate_legacy_orders"),
    ]

    operations = []
