# Generated by Django 6.0.4 on 2026-04-26 22:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("trade_in_payout", "Trade-In Payout"),
                            ("order_purchase", "Order Purchase"),
                            ("order_refund", "Order Refund"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_ledger_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeInRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved_pending_receipt", "Approved - Awaiting Cards"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=32,
                    ),
                ),
                (
                    "submission_method",
                    models.CharField(
                        choices=[
                            ("mail_in", "Mail-In"),
                            ("in_store_dropoff", "In-Store Drop-Off"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "estimated_total_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "final_payout_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("customer_notes", models.TextField(blank=True, default="")),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_ins_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_in_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeInItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=200)),
                ("set_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "card_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NM", "Near Mint"),
                            ("LP", "Lightly Played"),
                            ("MP", "Moderately Played"),
                            ("HP", "Heavily Played"),
                            ("DMG", "Damaged"),
                        ],
                        default="NM",
                        max_length=8,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "user_estimated_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trade_ins.tradeinrequest",
                    ),
                ),
            ],
        ),
    ]
