# Generated by GitHub Copilot on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_pokeshopsettings_trade_ins_enabled'),
        ('trade_ins', '0003_tradein_counteroffers_and_card_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinrequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='recurring_timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_requests', to='inventory.recurringtimeslot'),
        ),
        migrations.AddField(
            model_name='tradeinitem',
            name='tcgplayer_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
