# Generated by Django 6.0.4 on 2026-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_ins", "0004_pickup_slot_and_tcgplayer_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeinrequest",
            name="cash_payment_method",
            field=models.CharField(
                blank=True,
                choices=[("venmo", "Venmo"), ("zelle", "Zelle"), ("paypal", "PayPal")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tradeinrequest",
            name="payout_type",
            field=models.CharField(
                choices=[("store_credit", "Store Credit"), ("cash", "Cash")],
                default="store_credit",
                max_length=20,
            ),
        ),
    ]
