# Generated by Django 6.0.4 on 2026-04-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade_ins", "0005_tradeinrequest_cash_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradeinrequest",
            name="submission_method",
            field=models.CharField(
                choices=[("in_store_dropoff", "Drop-Off")], max_length=32
            ),
        ),
    ]
