# Generated by Django 6.0.4 on 2026-04-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_pickuptimeslot_pokeshopsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="go_live_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Item is hidden until this date/time. Null means immediately visible.",
                null=True,
            ),
        ),
    ]
