# Generated by Django 6.0.4 on 2026-04-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_item_go_live_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTimeslot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_bookings", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
