# Generated by Django 6.0.4 on 2026-04-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_tcgcardprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeshopsettings",
            name="discord_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Discord webhook URL for order notifications",
            ),
        ),
    ]
