# Generated by Django 6.0.4 on 2026-04-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_accesscode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-id"]},
        ),
        migrations.RenameField(
            model_name="item",
            old_name="go_live_date",
            new_name="published_at",
        ),
        migrations.AlterField(
            model_name="item",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the product page becomes visible. Null = hidden draft.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InventoryDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("drop_time", models.DateTimeField()),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_drops",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["drop_time"],
            },
        ),
    ]
