# Generated by Django 6.0.4 on 2026-04-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_tcg_facets_and_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tcg_artist",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tcg_hp",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="tcg_set_release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="tcg_subtypes",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated subtypes e.g. Basic, EX",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tcg_supertype",
            field=models.CharField(
                blank=True, help_text="Pokémon/Trainer/Energy", max_length=20, null=True
            ),
        ),
    ]
