# Generated by Django 6.0.4 on 2026-04-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_tcg_deep_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_core",
            field=models.BooleanField(
                default=False,
                help_text="Sacred-Three category — cannot be deleted or renamed",
            ),
        ),
    ]
