# Generated by Django 6.0.4 on 2026-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_category_is_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeshopsettings",
            name="public_discord_invite",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokeshopsettings",
            name="ucsc_discord_invite",
            field=models.URLField(blank=True, null=True),
        ),
    ]
