# Generated by Django 6.0.4 on 2026-04-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_item_max_per_user_default_unlimited"),
        ("inventory", "0023_pokeshopsettings_public_discord_invite_and_more"),
    ]

    operations = []
