# Generated by Django 6.0.4 on 2026-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_add_promo_banner_image_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="max_per_week",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max qty per user per rolling 7-day window. Null = no weekly limit.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="max_total_per_user",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max qty per user all-time. Null = no lifetime limit.",
                null=True,
            ),
        ),
    ]
