# Generated by Django 6.0.4 on 2026-04-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_pokeshopsettings_payment_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeshopsettings",
            name="announcement_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-clear announcement after this date/time",
                null=True,
            ),
        ),
    ]
