# Generated by Django 6.0.4 on 2026-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_announcement_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="preview_before_release",
            field=models.BooleanField(
                default=False,
                help_text="If True, page is visible now but shows 'Coming Soon' until published_at.",
            ),
        ),
    ]
