# Generated by Django 6.0.4 on 2026-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_item_show_when_out_of_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeshopsettings",
            name="trade_ins_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to submit new trade-in requests",
            ),
        ),
    ]
