# Generated by Django 6.0.4 on 2026-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_pokeshopsettings_trade_ins_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeshopsettings",
            name="trade_cash_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=65.0,
                help_text="Percentage of card value given as cash for trade payouts (e.g. 65 = 65%)",
                max_digits=5,
            ),
        ),
    ]
