# Generated by Django 6.0.4 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_pokeshopsettings_trade_cash_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgcardprice',
            name='card_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tcgcardprice',
            name='direct_low_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tcgcardprice',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tcgcardprice',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tcgcardprice',
            name='mid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tcgcardprice',
            name='price_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tcgcardprice',
            name='set_printed_total',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tcgcardprice',
            name='tcgplayer_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
