# Generated by Django 6.0.4 on 2026-05-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0037_backgroundjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeshopsettings",
            name="standard_illegal_sets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="TCG set names admins explicitly mark not Standard legal",
            ),
        ),
        migrations.AddField(
            model_name="pokeshopsettings",
            name="standard_legal_sets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="TCG set names admins explicitly mark Standard legal",
            ),
        ),
    ]
