# Generated by Django 6.0.4 on 2026-05-01 05:49

import inventory.standard_format
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0038_pokeshopsettings_standard_illegal_sets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeshopsettings",
            name="standard_illegal_marks",
            field=models.JSONField(
                blank=True,
                default=inventory.standard_format.default_standard_illegal_marks,
                help_text="Regulation marks admins explicitly mark not Standard legal",
            ),
        ),
        migrations.AddField(
            model_name="pokeshopsettings",
            name="standard_legal_marks",
            field=models.JSONField(
                blank=True,
                default=inventory.standard_format.default_standard_legal_marks,
                help_text="Regulation marks admins explicitly mark Standard legal",
            ),
        ),
    ]
