# Generated by Django 6.0.4 on 2026-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_wantedcard_remove_item_image_path_item_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
