# Generated by Django 6.0.4 on 2026-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_item_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupTimeslot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("max_bookings", models.PositiveIntegerField(default=5)),
                ("current_bookings", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="PokeshopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_credit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=85.0,
                        help_text="Percentage of card value given as trade credit (e.g. 85 = 85%)",
                        max_digits=5,
                    ),
                ),
                ("store_announcement", models.TextField(blank=True, default="")),
                ("max_trade_cards_per_order", models.PositiveIntegerField(default=5)),
            ],
            options={
                "verbose_name": "Pokeshop Settings",
                "verbose_name_plural": "Pokeshop Settings",
            },
        ),
    ]
