# Generated by Django 6.0.4 on 2026-04-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_recurringtimeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Brief summary shown on card listings",
                max_length=300,
            ),
        ),
    ]
