# Generated by Django 6.0.4 on 2026-04-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_item_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCGCardPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=300)),
                ("clean_name", models.CharField(db_index=True, max_length=300)),
                ("group_id", models.IntegerField()),
                ("group_name", models.CharField(max_length=200)),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "sub_type_name",
                    models.CharField(
                        blank=True,
                        default="Normal",
                        help_text="e.g. Normal, Holofoil, Reverse Holofoil",
                        max_length=80,
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("product_id", "sub_type_name")},
            },
        ),
    ]
