# Generated by Django 6.0.4 on 2026-04-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_pokeshopsettings_discord_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="wantedcard",
            name="tcg_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.tcgcardprice",
            ),
        ),
    ]
