# Generated by Django 6.0.4 on 2026-04-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_wantedcard_tcg_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="tcgcardprice",
            name="rarity",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Rare Holo, Common",
                max_length=100,
            ),
        ),
    ]
