# Generated by Django 6.0.4 on 2026-04-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_add_rarity_to_tcgcardprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "usage_limit",
                    models.PositiveIntegerField(default=1, help_text="0 = unlimited"),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Internal note, e.g. who this was issued for",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
