# Generated by Django 6.0.4 on 2026-04-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_published_at_and_inventory_drops"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                ("image_url", models.URLField()),
                (
                    "link_url",
                    models.CharField(
                        help_text="Absolute or relative URL", max_length=500
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("FULL", "Full"),
                            ("HALF", "Half"),
                            ("QUARTER", "Quarter"),
                        ],
                        default="QUARTER",
                        max_length=10,
                    ),
                ),
                ("position_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["position_order"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="api_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="pokemontcg.io card ID",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="card_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_holofoil",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="rarity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="tcg_set_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.category",
            ),
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("CAROUSEL", "Carousel"),
                            ("GRID", "Grid"),
                            ("HERO", "Hero"),
                        ],
                        max_length=10,
                    ),
                ),
                ("position_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="homepage_sections",
                        to="inventory.item",
                    ),
                ),
                (
                    "banners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="homepage_sections",
                        to="inventory.promobanner",
                    ),
                ),
            ],
            options={
                "ordering": ["position_order"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.subcategory",
            ),
        ),
    ]
