# Generated by Django 6.0.4 on 2026-04-12 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_category_promo_homepage_tcg_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="rarity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Common", "Common"),
                    ("Uncommon", "Uncommon"),
                    ("Rare", "Rare"),
                    ("Holo Rare", "Holo Rare"),
                    ("Ultra Rare", "Ultra Rare (ex/V/GX/EX)"),
                    ("Illustration Rare", "Illustration Rare (IR)"),
                    ("Special Illustration Rare", "Special Illustration Rare (SIR)"),
                    ("Gold Secret Rare", "Gold Secret Rare"),
                ],
                db_index=True,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tcg_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Stage 1", "Stage 1"),
                    ("Stage 2", "Stage 2"),
                    ("Mega", "Mega"),
                    ("BREAK", "BREAK"),
                    ("VMAX", "VMAX"),
                    ("VSTAR", "VSTAR"),
                    ("Tera", "Tera"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tcg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fire", "Fire"),
                    ("Water", "Water"),
                    ("Grass", "Grass"),
                    ("Psychic", "Psychic"),
                    ("Fighting", "Fighting"),
                    ("Darkness", "Darkness"),
                    ("Metal", "Metal"),
                    ("Lightning", "Lightning"),
                    ("Fairy", "Fairy"),
                    ("Dragon", "Dragon"),
                    ("Colorless", "Colorless"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
