# Generated by Django 6.0.4 on 2026-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_pokeshopsettings_last_discord_eod_summary_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="promobanner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="promo_banners/"),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
