# Generated by Django 6.0.4 on 2026-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_widen_payment_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="preferred_pickup_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
