# Generated by Django 6.0.4 on 2026-04-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_pickuptimeslot_pokeshopsettings"),
        ("orders", "0006_order_preferred_pickup_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_timeslot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.pickuptimeslot",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                    ("cash_needed", "Cash Payment Needed"),
                    ("trade_review", "Trade Under Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TradeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "credit_percentage",
                    models.DecimalField(decimal_places=2, default=85.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_offer",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeCardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=200)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("mint", "Mint / Near Mint"),
                            ("good", "Good"),
                            ("played", "Played / Light Play"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("ultra_rare", "Ultra Rare"),
                            ("secret_rare", "Secret Rare"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="trade_photos/")),
                (
                    "is_wanted_card",
                    models.BooleanField(
                        default=False,
                        help_text="True if this matches a card on our Wanted list",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=None,
                        help_text="Null=pending, True=accepted, False=denied",
                        null=True,
                    ),
                ),
                (
                    "trade_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="orders.tradeoffer",
                    ),
                ),
            ],
        ),
    ]
