# Generated by Django 6.0.4 on 2026-04-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_pickup_timeslot_alter_order_status_tradeoffer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradecarditem",
            name="is_accepted",
            field=models.BooleanField(
                default=None,
                help_text="Per-card accept/reject for partial trades. Null=pending, True=accepted, False=rejected",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradeoffer",
            name="trade_mode",
            field=models.CharField(
                choices=[
                    ("all_or_nothing", "All or Nothing"),
                    ("allow_partial", "Allow Partial"),
                ],
                default="all_or_nothing",
                max_length=20,
            ),
        ),
    ]
