# Generated by Django 6.0.4 on 2026-04-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_recurringtimeslot"),
        ("orders", "0008_tradecarditem_is_accepted_tradeoffer_trade_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_penalty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_date",
            field=models.DateField(
                blank=True,
                help_text="Specific date this recurring slot is booked for",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recurring_timeslot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.recurringtimeslot",
            ),
        ),
    ]
