# Generated by Django 6.0.4 on 2026-04-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_cancellation_penalty_order_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradecarditem",
            name="base_market_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Oracle base market price at time of checkout",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradecarditem",
            name="tcg_product_id",
            field=models.IntegerField(
                blank=True,
                help_text="TCGCSV product ID for oracle price lookup",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradecarditem",
            name="tcg_sub_type",
            field=models.CharField(
                blank=True, default="", help_text="e.g. Normal, Holofoil", max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="tradecarditem",
            name="condition",
            field=models.CharField(
                choices=[
                    ("near_mint", "Near Mint"),
                    ("lightly_played", "Lightly Played"),
                    ("moderately_played", "Moderately Played"),
                    ("heavily_played", "Heavily Played"),
                    ("damaged", "Damaged"),
                ],
                default="lightly_played",
                max_length=20,
            ),
        ),
    ]
