# Generated by Django 6.0.4 on 2026-04-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_uuid_overage_backup"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradecarditem",
            name="admin_override_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Admin-overridden trade credit value (replaces calculated credit)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
