# Generated by Django 6.0.4 on 2026-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_add_admin_override_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradecarditem",
            name="custom_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="User-provided expected value override",
                max_digits=10,
                null=True,
            ),
        ),
    ]
