# Generated by Django 6.0.4 on 2026-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_custom_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="counteroffer_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Admin message explaining the counteroffer to the user",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                    ("cash_needed", "Cash Payment Needed"),
                    ("trade_review", "Trade Under Review"),
                    ("pending_counteroffer", "Counteroffer Pending"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
