# Generated by Django 6.0.4 on 2026-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_counteroffer_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="resolution_summary",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Chronological event log for order timeline",
            ),
        ),
    ]
