# Generated by Django 6.0.4 on 2026-04-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_order_asap_reminder_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_acknowledged",
            field=models.BooleanField(
                default=False,
                help_text="Whether an ASAP order has been acknowledged by an admin",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="asap_reminder_level",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Highest automated admin reminder sent for this ASAP order",
            ),
        ),
    ]
