# Generated by Django 6.0.4 on 2026-04-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradecarditem",
            name="rarity",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
