# Generated by Django 6.0.4 on 2026-04-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_max_per_week_item_max_total_per_user"),
        ("orders", "0024_alter_tradecarditem_rarity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="specific_product",
        ),
        migrations.AddField(
            model_name="coupon",
            name="specific_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="If set, discount applies only to these products",
                to="inventory.item",
            ),
        ),
    ]
