# Generated by Django 6.0.4 on 2026-04-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_add_orderitem_and_nullable_order_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_rescheduled_by_user",
            field=models.BooleanField(
                default=False,
                help_text="True once the user uses their one-time voluntary reschedule",
            ),
        ),
    ]
