# Generated by GitHub Copilot on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_cancellation_reason_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradecarditem',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Card image URL from the TCG database', max_length=500),
        ),
        migrations.AddField(
            model_name='tradecarditem',
            name='tcgplayer_url',
            field=models.URLField(blank=True, default='', help_text='TCGPlayer listing/search URL used for price verification', max_length=500),
        ),
    ]
