# Generated by Django 6.0.4 on 2026-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_tradecarditem_card_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store_credit_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("venmo", "Venmo"),
                    ("zelle", "Zelle"),
                    ("paypal", "PayPal"),
                    ("cash", "Cash"),
                    ("store_credit", "Store Credit"),
                    ("trade", "Trade-In"),
                    ("cash_plus_trade", "Cash + Trade Difference"),
                ],
                max_length=20,
            ),
        ),
    ]
