# Generated by GitHub Copilot on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_pokeshopsettings_standard_illegal_marks_and_more'),
        ('orders', '0036_discordpickuplifecyclerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='specific_categories',
            field=models.ManyToManyField(
                blank=True,
                help_text='If set, discount applies to products in these categories',
                to='inventory.category',
            ),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_subcategories',
            field=models.ManyToManyField(
                blank=True,
                help_text='If set, discount applies to products in these subcategories',
                to='inventory.subcategory',
            ),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_tags',
            field=models.ManyToManyField(
                blank=True,
                help_text='If set, discount applies to products with these tags',
                to='inventory.itemtag',
            ),
        ),
    ]
