# Generated by Django 6.0.4 on 2026-04-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_botapikey_userprofile_discord_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokedex_number", models.IntegerField(db_index=True)),
                ("display_name", models.CharField(max_length=100)),
                ("region", models.CharField(db_index=True, max_length=50)),
                ("filename", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "ordering": ["pokedex_number", "display_name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pokemon_icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="users.pokemonicon",
            ),
        ),
    ]
