# Generated by Django 6.0.4 on 2026-04-17 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_pokemonicon_userprofile_pokemon_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has dismissed the strike warning",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "given_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="strikes_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
