# Generated by Django 6.0.4 on 2026-04-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_strike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strike",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
